# Generated by Django 3.2.4 on 2021-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Processing', 'Order Processing'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Processing', 'Order Processing'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=200),
        ),
    ]
